Migration from 4.7.x to 4.8.x
igniterealtime/Botz pull request #11
Opened 2024-06-24 20:58 UTC by sheldonrobinson

Fixes igniterealtime/Botz#10
Remove LocalClientSession from BotzConnection, see OF-2682: Move duplicate session management to new abstract Connection…
Implemented abstract method Connection.getTLSProtocolName() and Connection.getCipherSuiteName()
Updated login, see Issue 10, Failing to build with Openfire-4.8.x 
Bump version to 1.2.2-snapshot

2024-06-25 10:03 UTC, guusdk requested changes
This looks good, thanks! After reviewing, I've left a couple of minor requests.

Could you also update the readme file, to reflect the updated version number and usage pattern please?

2024-06-25 10:03 UTC, guusdk commented on src/main/java/org/igniterealtime/openfire/botz/BotzConnection.java
> +        return Optional.empty();
Why not do the same thing as with CipherSuiteName: check if the session is non-null, and then delegate to that.

2024-06-25 10:03 UTC, guusdk commented on pom.xml
> +            <version>4.8.1</version>
I _think_ this also works with 4.8.0 instead of 4.8.1? It might be good to be as liberal as possible.

2024-06-25 10:03 UTC, guusdk commented on pom.xml
> +    <version>1.2.2-SNAPSHOT</version>
This is quite a major change. I suggest bumping the version number to 1.3 instead of 1.2.2!

2024-06-26 22:18 UTC, sheldonrobinson commented
What did you mean by "update the readme file ... usage pattern"?

2024-06-27 07:19 UTC, guusdk commented
> What did you mean by "update the readme file ... usage pattern"?

This bit (the version number, and maybe the example code just above it): 
![image](https://github.com/igniterealtime/Botz/assets/4253898/60408dee-b41b-46ae-8391-3626bc07b22c)

2024-06-27 15:44 UTC, sheldonrobinson commented
No changes were necessary to the sample code.  It still works.  I have included a more complete example containing the other artifacts (plugin.xml, pom.xml and complete java code)

2024-06-28 08:00 UTC, guusdk commented
Thanks!

To get rid of warnings during the build, I've pushed a couple of additional minor changes:
- source encoding is now explicitly set in the pom.xml
- a version for a Maven plugin is explicitly set

I've also reworked your changes a bit, with regards to version numbering. I prefer that there is exactly one commit where the code lives under a particular non-SNAPSHOT version. If we use that commit for a release, then there can never be any ambiguity as to what state of the code belongs to what release. To do that, I've changed your commit where you introduced version `1.3.0` in such a way that it introduces `1.3.0-SNAPSHOT` instead. I've then added a commit that moves the version from `1.3.0-SNAPSHOT` to `1.3.0`, followed by another commit that moves it from `1.3.0` to `1.3.1-SNAPSHOT`. After merging this PR, I'll draft a release from that second-to-last commit.

2024-06-28 08:04 UTC, guusdk commented
As Openfire 4.8.0 drops support for Java 8, I've removed the CI builder for that version. I've also updated pom and the documentation to use the lowest version of Java that's now supported: 11.

2024-06-28 08:04 UTC, guusdk approved these changes

2024-06-28 08:05 UTC, merged